include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    cancel_subscriptions: true
    empty_constructor_bodies: true
    leading_newlines_in_multiline_strings: true
    prefer_contains: true
    prefer_mixin: true
    sized_box_for_whitespace: true
    sized_box_shrink_expand: true
    slash_for_doc_comments: true
    sort_child_properties_last: true
    sort_constructors_first: true
    unnecessary_lambdas: true
    unnecessary_string_interpolations: true
    use_string_buffers: true
    sort_pub_dependencies: true
    avoid_return_types_on_setters: true
    prefer_relative_imports: true